routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/status/{id}', 'TransactionController@status');
Route::delete('/requestform', 'RequestFormController@clear')->name('requestform.clear');

Route::resources([
	'categories' => 'CategoryController',
	'units' => 'UnitController',
	'transactions' => 'TransactionController',
	'requestform' => 'RequestFormController'
	
]);

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use App\Unit;
use App\Status;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use Illuminate\Contracts\Validation\Rule;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\DB;


class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        

      $transactions = Transaction::paginate(5);
      //returns an array
      //dd($transactions);

      $statuses = Status::all();
      $units = Unit::all();

      // if(request()->has('status')) {

      //   //$displays = Transaction::where('status', request('status'))->paginate(5);

      //   $displays = Transaction::where('status', request('status'))
      //       ->paginate(5)->appends('status', request('status'));


      // } else {

      // $displays = Transaction::paginate(5);

      // }

      // if(request()->has('status_id')){

      //   $transactions = $transactions->where('status_id', request('status_id'));
      // }

      //   $transactions = $transactions->paginate(5)->appends([
      //   'status_id' => request('status_id')
      // ]);




     // $posts = Transaction::paginate()

      return view('transactions.index', compact('transactions'))
        ->with('transactions', $transactions)
        ->with('statuses', $statuses);
        
        
         
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function rules()
    {

    }


    public function store(Request $request)
    {
        //validate dates
        $validatedData = $request->validate([
          'date_needed' => 'required',
          'date_return' => 'required|after_or_equal:date_needed',
          'reason' => 'required|string'

        ]);

        //dd($validatedData);

        //get the details needed 
        $transaction = new Transaction;
        //transaction_code
        $transaction->request_code = strtoupper(Str::random(10));

        //user_id
        $transaction->user_id = Auth::user()->id;
        $transaction->date_needed = $request->date_needed;
        $transaction->date_return = $request->date_return;

        //reason
        $transaction->reason = $request->reason;
        
        $transaction->save();
        //dd($transaction);



        $units = Unit::find(array_keys(session('requestform')));

        foreach ($units as $unit) {
          
          //product_id or unit_id
          $unit_id = $unit->id;

          $transaction_id = $transaction->id;

          //query to pivot table
          $transaction->units()->attach($unit->id,[
            'transaction_id' => $transaction_id,
            'unit_id' => $unit_id
          ]);
        }

        $transaction->save();
        //dd($transaction);

        session()->forget('requestform');

        return redirect( route('transactions.show', $transaction->id ));
          

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction) 
    {
        //
      
      $statuses = Status::all();
      return view('transactions.show')
        ->with('transaction', $transaction)
        ->with('statuses', $statuses)
        ->with('message', "Return date must be later than date needed");
        


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        //
        
          

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        //
      $transaction->status_id = $request->status_id;
      $transaction->save();
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }


    public function status($stat_id)
    {

        $statuses = Status::all();
        $transactions = DB::table('transactions')
            ->join('statuses', 'transactions.status_id', '=', 'statuses.id')
            ->select('transactions.*', 'statuses.*')
            ->where(['statuses.id' => $stat_id])
            ->get();
        //dd($transactions);

        return view('statuses.statusestransactions', ['statuses' => $statuses, 'transactions' => $transactions]);
            
    }
}

resources/views/transactions/partials/accordion.blade.php
<div class="accordion" id="accordionExample">

@cannot('isAdmin')  
  @foreach($transactions as $transaction)
    <?php $status = App\Status::find($transaction->status_id)?>
    
    {{-- <a href="{{ url("/pending/{$transaction->id}")}}"></a> --}}
    @if($transaction->user_id === Auth::user()->id)
      {{-- transaction card start --}}
      <div class="card">
        <div class="card-header" id="headingOneAccordion">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse{{$transaction->id}}" aria-expanded="true" aria-controls="collapseOne">
              {{$transaction->request_code}}
              <span class="badge badge-{{ $status->id == 1 ? 'success' : ($status->id == 2 ? 'warning' : 'danger')}}">
                  {{ $status->name}}  
              </span>
            </button>
          </h2>
        </div>

        <div id="collapse{{$transaction->id}}" class="collapse" aria-labelledby="headingOneAccordion" data-parent="#accordionExample">
          <div class="card-body">
            
            @include('transactions.partials.summary')
            <a href="{{route('transactions.show', $transaction->id)}}">
              View details
            </a>
          </div>
        </div>
      </div>
      {{-- transaction card start --}}
    @endif
  @endforeach
@endcannot


@can('isAdmin')
  @foreach($transactions as $transaction)
      <?php $status = App\Status::find($transaction->status_id)?>
      <?php $user = App\User::find($transaction->user_id)?>
      {{-- transaction card start --}}
      <div class="card">
        <div class="card-header" id="headingOne">
          <h2 class="mb-0">
            <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse{{$transaction->id}}" aria-expanded="true" aria-controls="collapseOne">
              {{$transaction->request_code}}
              {{-- <span class="badge badge-primary">
                {{$status->name}}
              </span> --}}
              <span class="badge badge-{{ $status->id == 1 ? 'success' : ($status->id == 2 ? 'warning' : 'danger')}}">
                  {{ $status->name}}  
              </span>
            </button>
          </h2>
        </div>

        <div id="collapse{{$transaction->id}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
          <div class="card-body">
            
            @include('transactions.partials.summary')
            <a href="{{route('transactions.show', $transaction->id)}}">View details</a>
          </div>
        </div>
      </div>
      {{-- transaction card start --}}

  @endforeach
@endcan

</div>

resources/views/transactions/partials/edit-status.blade.php
<form action="{{route('transactions.update',$transaction->id)}}" 
	method="post" 
	class=" border">
	@csrf
	@method("PUT")
	<label for="status_id">Edit:</label>
	<select name="status_id" id="status_id" class="form-control form-control-sm">
		@foreach($statuses as $status)
			<option value="{{$status->id}}">{{$status->name}}</option>
		@endforeach
	</select>
	<button class="btn btn-sm btn-outline-primary my-1">Edit Status</button>
</form>

resources/views/transactions/partials/header.blade.php
<h6>		
	<div class="input-group mb-3">
		<div class="input-group-text">
			<a 
				href="{{ route('transactions.index') }}" 
				class="mr-3 d-inline-block
				{{ Route::CurrentRouteNamed('transactions.index') ? "active1" : "" }}
				">
					All requests	
			</a>
		</div>
		

		{{-- start of search bar --}}
		  <div class="input-group-prepend ml-3">
		    <label class="input-group-text" 
		    	for="inputGroupSelect01">Sort by</label>
		  </div>
		  <select 
		  	class="custom-select" 
		  	id="inputGroupSelect01">
		    <option selected>...</option>
		    {{-- @foreach($categories as $category)
		    	<a href="{{ route('categories.show', $category->id)}}">
		    		<option value="{{ $category->id}}">{{ $category->name}}</option>
		    	</a>
			@endforeach --}}
		  </select>
		 {{-- end of search bar --}}
	</div>
		




</h6>

resources/views/transactions/partials/summary.blade.php
<div class="table-responsive">
	<?php $user = App\User::find($transaction->user_id)?>
	<?php $status = App\Status::find($transaction->status_id)?>
	<table class="table table-hover">
		{{-- transacation code --}}
		<tr>
			<td>Reference number:</td>
			<td>{{$transaction->request_code}}</td>
		</tr>
		{{-- transaction code end --}}
		
		{{-- Customer name start --}}
		<tr>
			<td>Customer</td>
			<td>{{ $user->name }}</td>
		</tr>
		{{-- Customer name end --}}

		{{-- Date start --}}
		<tr>
			<td>Date requested:</td>
			<td>{{ date("M d, Y", strtotime($transaction->created_at)) }}</td>
		</tr>
		{{-- Date end --}}


		{{-- Status start --}}
		<tr>
			<td>Status</td>
			<td>{{ $status->name}}</td>
			@can('isAdmin')
				<td>
					@include('transactions.partials.edit-status')
				</td>
			@endcan
		</tr>
		{{-- Status end --}}

		{{-- start of reason --}}
		<tr>
			<td>Reason for the request:</td>
			<td>{{ $transaction->reason}}</td>
		</tr>
		{{-- end of reason --}}

		{{-- borrow_date start --}}
		<tr>
			<td>Date needed:</td>
			<td>{{ date("M d, Y", strtotime($transaction->date_needed)) }}</td>
		</tr>
		{{-- borrow_date end --}}

		{{-- borrow_date start --}}
		<tr>
			<td>Date to return:</td>
			<td>{{ date("M d, Y", strtotime($transaction->date_return)) }}</td>
		</tr>
		{{-- borrow_date end --}}

		{{-- start of requested unit --}}
		<tfoot>
			<tr>
				<th>Requested Unit:</th>
			</tr>
			<tr>

				{{-- 
				@foreach($transaction->units as $unit)
=======
				{{<?php $units = App\Unit::findOrFail($transaction->unit->unit_id)?> --}}
				
				{{-- @foreach($transaction->units as $unit)
>>>>>>> feat-pagination
					
				<td>{{ $unit->unit_code}}</td>
				<td>{{ $unit->availability->name}}</td>

				@endforeach --}}
			</tr>
		</tfoot>
		{{-- end of requested unit --}}

	</table>
</div>
{{-- table end --}}

resources/views/transactions/partials/units-table.blade.php
<div class="row">
	<div class="col-12">
		{{-- table start --}}
		<div class="table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Asset Code</th>
						<th>Asset Type</th>
						<th>Particulars</th>
						<th>UOM</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					@foreach($transaction->units as $unit)
						<tr>
							<td>{{ $unit->unit_code}}</td>
							<td>{{ $unit->category->name}}</td>
							<td>{{ $unit->particulars}}</td>
							<td>{{ $unit->uom}}</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>
		{{-- table end --}}
	</div>
</div>