routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/status/{id}', 'TransactionController@status');
Route::delete('/requestform', 'RequestFormController@clear')->name('requestform.clear');

Route::resources([
	'categories' => 'CategoryController',
	'units' => 'UnitController',
	'transactions' => 'TransactionController',
	'requestform' => 'RequestFormController'
	
]);

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
    protected $fillable = ["name"];

    public function units(){

		return $this->hasMany('App\Unit');
	}
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Unit;
use Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Category $category)
    {
        // $this->authorize('viewAny', Category::class);
        $categories = Category::paginate(10)->sortBy('name');
        $units = Unit::all();
  
        return view('categories.index')
            ->with('categories', $categories)
            ->with('category', $category)
            ->with('units', $units);
          
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Category $category)
    {
        $this->authorize('create', Category::class);
        $categories = Category::all();
        $category = Category::find($category->id);

        return view('categories.index')
            ->with('categories', $categories)
            ->with('category', $category);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    { 
        $this->authorize('create', Category::class);
        $validatedData = $request->validate([
            'name' => 'required|unique:categories,name',
        ]);


        $category = new Category($validatedData);
        $category->save();

        return redirect( route('categories.index'))
            ->with('message', "Category '{$category->name}' is added successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //$this->authorize('view', $category);
        $units = Unit::all();
        $categories = Category::all()->sortBy('name');
        $unit_code = strtoupper(Str::random(6));


        return view('categories.show')
            ->with('category', $category)
            ->with('categories', $categories)
            ->with('units', $units)
            ->with('unit_code', $unit_code);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $this->authorize('update', $category);
        return view('categories.edit')
            ->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('update', $category);
        $validatedData = $request->validate([
            'name' => 'required|unique:categories,name'
        ]);
        $category->update($validatedData);
        $category->save();

        return redirect(route('categories.show', $category->id))
            ->with('message', "{$category->name} is updated successfully");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $this->authorize('delete', $category);
        $category->delete();

        return redirect(route('categories.index'));
    }
}

resources/views/categories/partials/add-asset-form.blade.php
					<form 
						action="{{ route('units.store')}}"
						method="post" 
						enctype="multipart/form-data" 
					>
						@csrf

						{{-- unit_code --}}
						<label for="unit_code">Unit Code:</label>
						<div class="input-group">
							<div class="input-group-prepend">
						    <span class="input-group-text" id="input_code">
						    	{{ $category->id}}
						    </span>
						  </div>
							
							<input 
								type="text" 
								name="unit_code" 
								id="unit_code" 
								class="form-control" 
								value="{{ $unit_code}}" 
								
								 
								>
						</div>
						@error('unit_code')
						<small class="d-block invalid-feedback">
							<strong>
								{{ $message }}
							</strong>
						</small>
						@enderror

						{{-- start category_id --}}
						<label for="category_id" class="mt-1">Asset category:</label>
						<select 
							name="category_id" 
							id="category_id" 
							class="form-control form-control-sm"
							readonly
						>
							
							<option value="{{ $category->id}}">
									{{ $category->name}}
							</option>

						</select>
						@error('category_id')
							<small class="d-block invalid-feedback">
								<strong>							
									{{ $message }}
								</strong>
							</small>
						@enderror
						{{-- end category_id --}}

						{{-- particulars --}}
						@include('units.partials.form-group',[
							'name' => 'particulars',
							'type' => 'text',
							'classes' => ['form-control', 'form-control-sm']
						])


						{{-- UOM --}}
						@include('units.partials.form-group',[
							'name' => 'uom',
							'type' => 'text',
							'classes' => ['form-control', 'form-control-sm']
						])

						{{-- image --}}
						@include('units.partials.form-group',[
							'name' => 'image',
							'type' => 'file',
							'classes' => ['form-control-file', 'form-control-sm', 'text-center', 'pl-0']
						])

						<button class="btn btn-sm btn-warning mt-1">Add Unit</button>

					</form>

resources/views/categories/partials/admin.blade.php
<div class="my-1">
		<p>
			<a 
			class="btn btn-success" 
			data-toggle="collapse" 
			href="#collapseExampleAddAsset" 
			role="button" 
			aria-expanded="false" 
			aria-controls="collapseExampleAddAsset">
						<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							<path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
							<path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
						</svg>
						 Add Asset
			</a>
		</p>
		<div 
			class="collapse" 
			id="collapseExampleAddAsset">
			<div class="card card-body">
				@include('categories.partials.add-asset-form')
			</div>
		</div>
</div>

resources/views/categories/partials/card.blade.php
  <div class="col-md-8 border-bottom border-bottom-info">
    <div class="card-body">
      <h5 class="card-title justify-content-left">
        {{ $category->name}}
      </h5>
      <p class="card-text">
        Current available: {{ collect($units)->where('category_id',$category->id)->where('availability_id',1)->count()}}
          /{{ collect($units)->where('category_id',$category->id)->count()}}
      </p>
    </div> 
  </div>

  <div class="col-md-4 border-bottom border-bottom-info">
    <div class="card-body">
      <div class="card-title">
         @if(!isset($view))
            {{-- start of view --}}
            <a 
              href="{{ route('categories.show', $category->id)}}" 
              class="btn btn-success">
                View
            </a>
            {{-- end of view --}}
          @endif 

        @can('isAdmin')
        {{-- start of edit --}}
          @include('categories.partials.edit-modal')
        {{-- end of edit --}}

        {{-- start of delete --}}
          <form action="{{ route('categories.destroy', $category->id) }}" method="post" 
            class="d-inline-block">
            @csrf
            @method('DELETE')

            <button class="btn btn-danger">Delete</button>
          </form>
          {{-- end of delete --}}
        @endcan
      </div>
    </div> 
  </div>




  

resources/views/categories/partials/create-modal.blade.php
<button 
  type="button" 
  class="btn btn-primary" 
  data-toggle="modal" 
  data-target="#exampleModalAddCat" 
  data-whatever="Add">
  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
      <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
  </svg>
  New Category

</button>


<div class="modal fade" id="exampleModalAddCat" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelAddCat" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabelAddCat">New Category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{{ route('categories.store') }}" method="post">
          @csrf

          <label for="name">Asset category:</label>
          <input 
            type="text" 
            name="name" 
            id="name" 
            class="form-control form-control-sm"
            required
          >
          <button class="btn btn-sm btn-primary mt-1">Add</button>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/categories/partials/edit-modal.blade.php
<button 
  type="button" 
  class="btn btn-warning" 
  data-toggle="modal" 
  data-target="#exampleModalEdit" 
  data-whatever="Edit">
  Edit

</button>


<div class="modal fade" id="exampleModalEdit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Category</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {{-- start of form --}}
        <form action="{{ route('categories.update', $category->id)}}" method="post" class="mt-2">
          @csrf
          @method('PUT')
          

          <label for="name">Asset category:</label>
          <input 
            type="text" 
            name="name" 
            id="name"
            class="form-control form-control-sm" 
            value="{{ $category->name}}"
          >
          <button class="btn btn-sm btn-warning mt-1">Save changes</button>
        </form>
        {{-- end of form --}}


      </div>
    </div>
  </div>
</div>

resources/views/categories/partials/header.blade.php
<h6>
			
	<div class="input-group mb-3">
		<div class="input-group-text">
			<a 
				href="{{ route('categories.index') }}" 
				class="mr-3 d-inline-block
				{{ Route::CurrentRouteNamed('categories.index') ? "active1" : "" }}
				">
					All categories	
			</a>
		</div>
		

		{{-- start of search bar --}}
		  <div class="input-group-prepend ml-3">
		    <label class="input-group-text" 
		    	for="inputGroupSelect01">Search</label>
		  </div>
		  <select 
		  	class="custom-select" 
		  	id="inputGroupSelect01">
		    <option selected>...</option>
		    @foreach($categories as $category)
		    	<a href="{{ url("category/{$category->id}") }}">
		    		<option value="{{ $category->id}}">{{ $category->name}}</option>
		    	</a>
			@endforeach
		  </select>
		 {{-- end of search bar --}}
	</div>
		




</h6>

resources/views/categories/partials/user.blade.php
				<div class="input-group">
					<div class="input-group-text">
						
					</div>
					

					{{-- start of search bar --}}
					  {{-- <div class="input-group-prepend ml-3">
					    <label class="input-group-text" 
					    	for="inputGroupSelect01">Search</label>
					  </div>
					  <select 
					  	class="custom-select" 
					  	id="inputGroupSelect01">
					    <option selected>Categories...</option> --}}
					    {{-- @foreach($categories as $category)
					    	<a href="{{ route('categories.show', $category->id)}}">
					    		<option value="{{ $category->id}}">{{ $category->name}}</option>
					    	</a>
							@endforeach --}}
					  </select>
					 {{-- end of search bar --}}
				</div>
		</div>
	
		<hr>

		<div class="row">
				@include('categories.partials.card', ['view' => false])
		</div>

		{{-- start of units display --}}
		<div class="row mt-3">
			@foreach($units as $unit)
				@if($category->id === $unit->category_id)
				<div class="col-12 col-md-4 mx-auto">
					
						{{-- start of unit card --}}
						<div class="card">
							<a 
								href="{{ route('units.show', $unit->id)}}">
								<img src="{{ $unit->image}}" alt="" class="card-img-top">
							</a>
							<div class="card-body">
								
								{{-- start of unit-code --}}
								<p class="card-text">
									<strong>
									Control code: {{ strtoupper($unit->unit_code)}}
									</strong>
								</p>
								{{-- end of unit_code --}}

								{{-- start of unit status --}}
								<p class="card-text">
										Status:
										<span class="badge badge-{{ $unit->availability_id == 1 ? 'success' : ($unit->availability_id == 2 ? 'warning' : 'danger')}}">
										{{ $unit->availability->name}}	
										</span>
								</p>
								{{-- end of unit status --}}

								{{-- start of unit category, particulars, and UOM --}}
								<button
									class="btn btn-sm border-none" 
									type="button" 
									data-toggle="collapse" 
									data-target="#collapseExample{{ $unit->unit_code}}" 
									aria-expanded="false" 
									aria-controls="collapseExample{{ $unit->unit_code}}">
								    Details
								 </button>

								 <div class="collapse" id="collapseExample{{ $unit->unit_code}}">
									  <div class="card card-body">
									  	<p class="card-text">
									  		Asset category: {{ $unit->category->name}}
									  	</p>
									    <p class="card-text"> 
												Particulars: {{ $unit->particulars}}
												<small class="d-block">
												UOM: {{ $unit->uom}}
												</small>
											</p>
									  </div>
									</div>
								{{-- end of unit category, particulars, and UOM --}}


								

								{{-- start of request --}}
								@cannot('isAdmin')
										@include('units.partials.request-form')
								@endcannot
								{{-- end of request --}}

								{{-- start of view btn --}}
								@if(!isset($view))
									<a href="{{ route('units.show', $unit->id)}}" class="btn btn-sm btn-info w-100 mt-1">
											View
										</a>
								@endif
								{{-- end of view btn --}}
								
								@can('isAdmin')
									{{-- start of edit btn --}}
									@include('units.partials.edit-btn')
									{{-- end of edit btn --}}

									{{-- start of delete btn --}}
									@include('units.partials.delete-form')
									{{-- end of delete btn --}}
								@endcan

							</div>

						</div>
						{{-- end of unit card --}}
				</div>
				@endif
			@endforeach
		</div>
		{{-- end of units display --}}